
project_id = "mtbcrbfchoqterxevvft"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true

[functions]
[functions.generate-evaluation]
verify_jwt = false
[functions.summarize-document]
verify_jwt = false
[functions.generate-course]
verify_jwt = false
[functions.generate-exercises]
verify_jwt = false
[functions.generate-control]
verify_jwt = false
