// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtbcrbfchoqterxevvft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YmNyYmZjaG9xdGVyeGV2dmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NDUwNzUsImV4cCI6MjA1NzEyMTA3NX0.97PG3U92JkmrsoxmxFNxiFMwxsHc8GnQM8Xpailfhy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);